services:
  - type: web
    name: chess-telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python chess_bot.py
    envVars:
      - key: TOKEN
        sync: false